blueprint:
  name: Increase light brightness based on lumix level
  description:
    This blueprint creates an automation that gradually increases the brightness
    of your lights when the lumix level falls below a certain value.
  domain: automation
  author: "@fredericomcorda"
  input:
    condition_entity:
      name: Condition Entity
      description: The entity to check the state of before running the automation
      selector:
        entity:
          multiple: false
    condition_state:
      name: Condition State
      description:
        The state that the condition entity must be in for the automation
        to run
    lumix_sensor:
      name: Lumix Sensor
      description: The sensor that measures the lumix level
      selector:
        entity:
          filter:
            - domain:
                - sensor
          multiple: false
    lumix_level:
      name: Lumix Level
      description:
        The lumix level at which the lights should start increasing in
        brightness
      default: 10
      selector:
        number:
          min: 0.0
          max: 100.0
          step: 1.0
          mode: slider
    light_entities:
      name: Lights
      description: The lights to control
      selector:
        target:
          entity:
            - domain:
                - light
  source_url: https://raw.githubusercontent.com/fredericomcorda/Home-Assistant-Blueprints/main/Control_Lights_Lumix.yaml

trigger:
  platform: numeric_state
  entity_id: !input lumix_sensor
  below: !input lumix_level

condition:
  condition: state
  entity_id: !input condition_entity
  state: !input condition_state

action:
  - repeat:
      while:
        - condition: numeric_state
          entity_id: !input lumix_sensor
          below: !input lumix_level
      sequence:
        - service: light.turn_on
          target: !input light_entities
          data_template:
            brightness_pct: "{{ state_attr(!input light_entities.entity_id, 'brightness') | int + 1 }}"
        - delay:
            seconds: 1

